core/urls.py
from django.urls import path, include
from django_registration.backends.one_step.views import RegistrationView

from . import views
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/login/', views.redirect_login, name='redirect-login'),
    path('/accounts/password/reset/', views.redirect_password_reset, name='redirect_password_reset'),
    path('login/', views.CustomizedLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    # path('register/', RegistrationView.as_view(success_url='/'), name='django_registration_register'),
    # path('register/', RegistrationView.as_view(form_class=views.MyCustomUserForm, success_url='/'), name='django_registration_register'),

    path('lesson/list/', views.LessonListView.as_view(), name='lesson_list'),

    path('sport/list/', views.SportListView.as_view(), name='sport_list'),
    # path('sport/detail/<int:pk>', views.SportDetailView.as_view(), name='sport_detail'),
    path('lesson/detail/<int:pk>/', views.LessonDetailView.as_view(), name='lesson_detail'),
    path('lesson/list/liked', views.LikedLessonListView.as_view(), name='liked_lesson_list'),

    path('user/create/', views.user_create, name='user_create'),
    path('profile/create/', views.ProfileCreateView.as_view(), name='profile_create'),
    path('profile/update/<int:pk>/', views.ProfileUpdateView.as_view(), name='profile_update'),

    path('like/create_delete/', views.like_create_delete, name='like_create_delete'),

    path('review/delete/', views.review_delete, name='review_delete'),
    path('review/create_update/', views.review_create_update, name='review_create_update'),

    path('wronginfo/create/', views.wronginfo_create, name='wronginfo_create'),

]

dailympic/urls.py
import re

from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url
from board.views import upload_attachment
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

from django.views.static import serve
from django.urls import re_path
import re

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('community/', include('board.urls'), name='community'),
    url(r'^summernote/upload_attachment/$', upload_attachment, name='django_summernote-upload_attachment'),
    path('summernote/', include('django_summernote.urls')),
    # path('',include('social_django.urls', namespace='social'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django import template
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


register = template.Library()


class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='profile',
        verbose_name="유저",
    )
    image = models.ImageField(
        default=None,null=True,blank=True,verbose_name='프로필 사진',
        upload_to='profile/%Y/%m/%d',
    )
    name = models.CharField(max_length=31, verbose_name='이름')
    SEX_CHOICES = (
        ('M', '남'),
        ('W', '여')
    )
    sex = models.CharField(max_length=7, choices=SEX_CHOICES, verbose_name='성별', default='W')
    birthday = models.DateField(verbose_name='생년월일')
    phone = models.CharField(
        max_length=31,
        verbose_name='휴대전화',
        default='등록된 전화번호가 없습니다.'
    )

    def __str__(self):
        return self.user.username+'의 프로필'

    class Meta:
        verbose_name = '프로필'
        verbose_name_plural = '프로필'


class Sport(models.Model):
    name = models.CharField(
        max_length=255, verbose_name='종목명',
    )
    icon = models.ImageField(
        default=None, null=True, blank=True,
        upload_to='sports/',
        verbose_name='종목 아이콘',
    )

    class Meta:
        verbose_name = '종목'
        verbose_name_plural = '종목'

    def __str__(self):
        return self.name


class BigDistrict (models.Model):
    # 서울시 마포구
    name = models.CharField(
        max_length=31, verbose_name='시군구',
    )
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '시군구'
        verbose_name_plural = '시군구'


class SmallDistrict (models.Model):
    # 신수동
    name = models.CharField(
        max_length=15, verbose_name="동읍리",
    )
    big_district = models.ForeignKey(
        BigDistrict,
        on_delete=models.CASCADE,
        related_name='small_districts',
        verbose_name = "시군구",
    )

    def __str__(self):
        return self.big_district.name + ' ' + self.name

    class Meta:
        verbose_name = '동읍리'
        verbose_name_plural = '동읍리'


class Academy(models.Model):
    sport = models.ForeignKey(
        Sport,
        on_delete=models.CASCADE,
        verbose_name='종목', related_name='academies',
    )
    name = models.CharField(max_length=255, verbose_name='업체명')
    profile_image = models.ImageField(
        default=None, null=True, blank=True,
        upload_to='academy/%Y/%m/%d',
        verbose_name='업체 프로필 이미지',
    )
    introduction = models.TextField(
        blank=True, null=True, verbose_name='업체 소개',
    )
    phone = models.CharField(
        max_length=31, verbose_name='업체 문의번호', default='-1'
    )
    email = models.EmailField(
        blank=True, null=True, verbose_name='업체 이메일', default='-1'
    )
    operation_time = models.TextField(
        default='업체에 문의해주세요!', max_length=255,
        verbose_name='업체 운영 시간',
        help_text='엔터로 구분해주세요. (ex)월,목 - 17:00 ~ 20:00 (enter키) 금 - 18:00 ~ 20:00'
    )
    instagram = models.URLField(default='-1',
                                verbose_name='인스타그램 링크')
    facebook = models.URLField(default='-1',
                               verbose_name='페이스북 링크')
    website = models.URLField(default='-1',
                              verbose_name='웹사이트/카페 링크')
    small_district = models.ForeignKey(
        SmallDistrict,
        on_delete=models.CASCADE,
        related_name='locations',
        default=1,
        verbose_name='업체 위치 행정동'
    )
    # 중앙로 23길 3층 서강클라이밍
    address = models.CharField(
        max_length=255, default='업체에 문의해주세요!',
        verbose_name='업체 세부 주소',
    )

    lati = models.FloatField(default=0, verbose_name='위도')
    long = models.FloatField(default=0, verbose_name='경도')

    class Meta:
        verbose_name = '업체'
        verbose_name_plural = '업체'

    def __str__(self):
        return "["+str(self.sport.name)+"] "+str(self.name)


class Coach(models.Model):
    name = models.CharField(
        max_length=255, verbose_name='코치 이름',
    )
    academy = models.ForeignKey(
        Academy, on_delete=models.CASCADE,
        verbose_name='소속 업체', related_name='coaches',
    )
    career = models.TextField(
        verbose_name= '코치 커리어',
        help_text= '경력을 엔터로 구분해주세요',
        null=True,
        blank=True
    )
    introduction = models.TextField(
        blank=True, null=True, verbose_name='코치 짧은 소개',
    )
    phone = models.CharField(
        max_length=255, verbose_name='코치 번호',
        default='-1',
    )
    email = models.EmailField(
        verbose_name='코치 이메일', default='-1', blank=True, null=True,
    )
    instagram = models.URLField(
        null=True, blank=True, default='-1',
        verbose_name='코치 인스타그램 링크'
    )
    facebook = models.URLField(
        null=True, blank=True, default='-1',
        verbose_name='코치 페이스북 링크'
    )
    image = models.ImageField(
        verbose_name='코치 사진',
        null=True, blank=True, upload_to='coach/%Y/%m/%d'
    )

    class Meta:
        verbose_name = '코치'
        verbose_name_plural = '코치'

    def __str__(self):
        return '['+str(self.academy.name)+'] '+str(self.name)


class LessonType(models.Model):
    name = models.CharField(
        max_length=127,
        verbose_name='레슨 유형',
    )
    CLASSIFED_CHOICE_SET = (
        ('RECRUIT', 'RECRUIT'),
        ('METHOD', 'METHOD')

    )
    classified_as = models.CharField(
        max_length=127,
        verbose_name='대분류',
        default='METHOD',
        choices=CLASSIFED_CHOICE_SET,
    )

    class Meta:
        verbose_name = '레슨 유형'
        verbose_name_plural = '레슨 유형'

    def __str__(self):
        return '(' + str(self.pk) + ')' + str(self.name)


class LessonWeekFrequency(models.Model):
    freq = models.PositiveSmallIntegerField(
        unique=True,
        verbose_name='주 레슨 횟수'
    )
    displayed_as = models.CharField(
        verbose_name='표시 이름',
        max_length=31,
    )

    class Meta:
        verbose_name = '레슨 횟수'
        verbose_name_plural = '레슨 횟수'

    def __str__(self):
        return self.displayed_as


class Lesson(models.Model):
    academy = models.ForeignKey(
        Academy,
        null=True,
        on_delete=models.CASCADE,
        related_name='lessons',
        verbose_name='소속 업체'
    )
    title = models.CharField(max_length=255, verbose_name='레슨 이름')
    org_price = models.PositiveIntegerField(
        verbose_name='정가', default=0
    )
    dc_price = models.PositiveIntegerField(
        verbose_name='할인가', null=True, blank=True
    )
    lesson_time = models.TextField(
        default='코치에게 문의해주세요!',
        max_length=255, verbose_name='레슨 시간',
        help_text='엔터로 구분해주세요. (ex)월,목 - 17:00 ~ 20:00 (enter키) 금 - 18:00 ~ 20:00'
    )
    week_frequency = models.ManyToManyField(
        LessonWeekFrequency,
        related_name='lessons',
        related_query_name='week_frequencies',
        verbose_name='주간 횟수',
    )
    coach = models.ManyToManyField(
        Coach,
        related_name='lessons',
        related_query_name='coaches',
        verbose_name='코치'
    )
    introduction = models.CharField(
        max_length=127, default='  ',
        verbose_name="레슨 짧은 소개",
        help_text='레슨 리스트에서 보여지는 짧은 문구입니다'
    )
    description = models.TextField(
        null=True, blank=True,
        verbose_name='레슨 상세 설명'
    )
    # LESSON_TYPE_CHOICES = (
    #     ('ONE_DAY', '원데이 레슨'),
    #     ('ONE_POINT', '원포인트 레슨'),
    #     ('SHORT_TERM', '단기간 레슨'),
    #     ('LONG_TERM', '장기간 레슨'),
    #     ('ONE_TO_ONE', '1:1 레슨'),
    #     ('SMALL_GROUP', '소규모 그룹 레슨'),
    #     ('LARGE_GROUP', '대규모 그룹 레슨'),
    # )
    lesson_type = models.ManyToManyField(
        LessonType,
        verbose_name='레슨 유형',
        related_name='lessons',
    )
    rating_total = models.BigIntegerField(
        default=0,
        verbose_name='레슨 평점 총합'
    )
    review_count = models.PositiveIntegerField(
        default=0,
        verbose_name='후기 개수'
    )
    rating = models.FloatField(
        default=0,
        verbose_name='레슨 평점'
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        null=True,
        blank=True,
        verbose_name='작성일자'
    )
    likes_count = models.PositiveIntegerField(
        default=0,
        verbose_name='찜한 유저 수'
    )

    class Meta:
        verbose_name = '레슨'
        verbose_name_plural = '레슨'

    def __str__(self):
        return '('+str(self.id)+')['+str(self.academy.name)+'] ' + str(self.title)


class LessonImage(models.Model):
    lesson = models.ForeignKey(
        Lesson,
        on_delete=models.CASCADE,
        verbose_name='레슨'
    )
    image = models.ImageField(
        upload_to='lesson/%Y/%m/%d',
        verbose_name='레슨 이미지'
    )

    class Meta:
        verbose_name = '레슨 이미지'
        verbose_name_plural = '레슨 이미지'


class Review(models.Model):
    lesson = models.ForeignKey(
        Lesson,
        on_delete=models.CASCADE,
        related_name='reviews',
        verbose_name='레슨'
    )
    written_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='reviews',
        verbose_name='작성자'
    )
    rating = models.IntegerField(
        verbose_name='레슨 평점'
    )
    comment = models.CharField(
        max_length=255, verbose_name='후기내용',
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        null=True,
        blank=True,
        verbose_name='작성시간',
    )

    class Meta:
        ordering = ['-created_at']
        verbose_name = '후기'
        verbose_name_plural = '후기'

    def __str__(self):
        return self.comment + '('+self.lesson.title+')'


class Like (models.Model):
    liked_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE, related_name='likes',
        verbose_name='유저'
    )
    lesson = models.ForeignKey(
        Lesson,
        on_delete=models.CASCADE, related_name='likes',
        verbose_name='레슨',
    )

    class Meta:
        verbose_name = '찜'

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from .models import Profile
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    error_messages = {
        'password_mismatch': '비밀번호가 일치하지 않습니다.',
    }
    username = forms.CharField(label='아이디')
    email = forms.EmailField(label='이메일')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['email'] = forms.EmailField(
            label='이메일', required=True)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email is None:
            raise forms.ValidationError('email input error')
        return email

    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ('user',)


class CustomizedAuthenticationForm(AuthenticationForm):
    username = forms.CharField(label='아이디')

core/templates/user/bootstrap.html
<!DOCTYPE html>
{% load bootstrap4 %}
{% if 'use_i18n'|bootstrap_setting %}
    {% load i18n %}
    {% get_current_language as LANGUAGE_CODE %}
{% endif %}
<html lang="{{ LANGUAGE_CODE|default:'en_us' }}">

<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% if 'javascript_in_head'|bootstrap_setting %}
        <!-- Bootstrap JavaScript if it is in head -->
        {% bootstrap_javascript %}
    {% endif %}
    <title>Dailympic - 일상에 올림픽을 더하다</title>
    {% block bootstrap4_extra_head %}{% endblock %}

</head>

<body>
<div class="body">
    {% block bootstrap4_before_content %}{% endblock %}
    {% block bootstrap4_content %} CONTENT {% endblock %}
    {% block bootstrap4_after_content %}{% endblock %}
    {% block bootstrap4_extra_script %}{% endblock %}
</div>
</body>

</html>

core/templates/user/index.html
{% extends 'user/base.html' %}
{% load staticfiles %}
{% load humanize %}
{% block base_extra_head %}
    <link rel="stylesheet" href="https://unpkg.com/swiper/css/swiper.min.css">
    <style>
        .wrapper { float: left; clear: left; display: table; table-layout: fixed; }
        img.img-responsive { display: table-cell; max-width: 100%; }
        .card-img-top {
            height: 280px;
        }
        @media screen and (max-width: 600px) {
            .main_menu1_contents{background-color: #F1F3F4; height:180px;}
            .card-img-top {height: 120px;}
        }
        .swiper-slide { text-align: center; font-size: 18px; background: #fff; display: -webkit-box; display: -ms-flexbox; display: -webkit-flex; display: flex; -webkit-box-pack: center; -ms-flex-pack: center; -webkit-justify-content: center; justify-content: center; -webkit-box-align: center; -ms-flex-align: center; -webkit-align-items: center; align-items: center;}
        .card-text {white-space: normal; line-height: 1.2; height: 2.4em; text-align: left; word-wrap: break-word; display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical;
            display: inline-block; width: 100%; overflow: hidden; text-overflow: ellipsis;}
        .elipsis_text {white-space: normal; line-height: 1.2; height: 2.4em; text-align: left; word-wrap: break-word; display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical;
            display: inline-block; width: 100%; overflow: hidden; text-overflow: ellipsis;}
        .elipsis_text2 {white-space: normal; line-height: 1.2; height: 1.2em; text-align: left; word-wrap: break-word; display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical;
            display: inline-block; width: 100%; overflow: hidden; text-overflow: ellipsis;}
        .card-title {font-size: 12px;}
    </style>
{% endblock %}
{% block maincontent %}
    <div class="swiper-container">
        <div class="swiper-wrapper">
            <div class="swiper-slide"><a class="wrapper" href=""><img class="img-responsive" src="{% static 'img/메인배너1.jpg' %}" alt=""></a></div>
        </div>
        <div class="swiper-pagination"></div>
    </div>

    <section id="main_menu1" class="my-2">
        <div class="d-flex justify-content-between text-center">
            <a href="{% url 'sport_list' %}" class="mx-1" style="width: 33%; cursor: pointer; text-decoration: none; color: black;">
                <div class="w-100 text-center rounded p-1 main_menu1_contents">
                    <div class="w-100 p-4"><img src="{% static 'img/종목보기초록.png' %}" alt="" class="img-fluid"></div>
                    <h6 style="font-weight: bold;">종목</h6>
                    <h6 style="font-weight: bold;">보기</h6>
                </div>
            </a>
            <a href="/lesson/list/?type=1" class="mx-1" style="width: 33%; cursor: pointer; text-decoration: none; color: black;">
                <div class="w-100 text-center rounded p-1 main_menu1_contents">
                    <div class="w-100 p-4"><img style="width: 47%;" src="{% static 'img/원데이초록.png' %}" alt="" class="img-fluid"></div>
                    <h6 style="font-weight: bold;">원데이</h6>
                    <h6 style="font-weight: bold;">클래스</h6>
                </div>
            </a>
            <a href="{% url 'lesson_list' %}" class="mx-1" style="width: 33%; cursor: pointer; text-decoration: none; color: black;">
                <div class="w-100 text-center rounded p-1 main_menu1_contents">
                    <div class="w-100 p-4"><img src="{% static 'img/레슨보기초록.png' %}" alt="" class="img-fluid"></div>
                    <h6 style="font-weight: bold;">레슨</h6>
                    <h6 style="font-weight: bold;">보기</h6>
                </div>
            </a>
        </div>
    </section>

    <hr>

    <section id="main_menu2">
        <div class="index_hot d-flex justify-content-between px-3">
            <div style="font-size: 18px;">지금 <span style="color: red; font-weight: bold;">HOT</span> 한 수업 보기</div>
            <div><a href="/lesson/list/?order=추천순" style="text-decoration: none; color: #707070; font-size: 18px;">전체보기</a></div>
        </div>
        <div class="row w-100 mx-0 px-2">
            {% for lesson in hot_lessons %}
                <div class="col-lg-4 col-md-6 col-sm-6 col-6 p-2">
                    <div class="card" style="background-color: #E7E6E6;">
                        <a href="{% url 'lesson_detail' lesson.id %}" style="text-decoration: none; color: black;">
                            {% if lesson.lessonimage_set.exists %}
                                <img src="{{ lesson.lessonimage_set.first.image.url }}" class="card-img-top" alt="...">
                            {% else %}
                                <img src="{% static 'img/default_lesson_image.png' %}" class="card-img-top" alt="">
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title elipsis_text">{{ lesson.title }}</h5>
                                <p class="elipsis_text2" style="color: #707070; font-size: 12px; font-weight: bold;">{{ lesson.academy.name }}</p>
                                <p class="card-text">{{ lesson.introduction }}</p>
                                {% if  not lesson.dc_price or lesson.dc_price == 0 %}
                                    <h6 class="card-title">{{ lesson.org_price|intcomma }}원</h6>
                                {% else %}
                                    <h6 class="card-title">{{ lesson.dc_price|intcomma }}원 <small>{{ lesson.org_price|intcomma }}원</small></h6>
                                {% endif %}
                                <div class="d-flex justify-content-between">
                                    <p class="badge badge-danger">HOT</p>
                                    <p class="badge badge-success">{{ lesson.academy.small_district.big_district }}</p>
                                </div>
                            </div>
                        </a>

                    </div>
                </div>
            {% endfor %}
        </div>
    </section>

    <hr>

    <section id="main_menu3 my-3">
        <div class="index_hot d-flex justify-content-between px-3">
            <div style="font-style: italic; font-size: 18px;"><span style="color: blue; font-weight: bold;">NOW</span> OPEN</div>
            <div><a href="/lesson/list/?order=최신순" style="text-decoration: none; color:#707070; font-size: 18px;">전체보기</a></div>
        </div>


        <div class="row w-100 mx-0 px-2">
            {% for lesson in recent_lessons %}
                <div class="col-lg-4 col-md-6 col-sm-6 col-6 p-2">
                    <div class="card" style="background-color: #E7E6E6;">
                        <a href="{% url 'lesson_detail' lesson.id %}" style="text-decoration: none; color: black;">
                            {% if lesson.lessonimage_set.exists %}
                                <img src="{{ lesson.lessonimage_set.first.image.url }}" class="card-img-top" alt="...">
                            {% else %}
                                <img src="{% static 'img/default_lesson_image.png' %}" class="card-img-top" alt="">
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title elipsis_text">{{ lesson.title }}</h5>
                                <p class="elipsis_text2" style="color: #707070; font-size: 12px; font-weight: bold;">{{ lesson.academy.name }}</p>
                                <p class="card-text">{{ lesson.introduction }}</p>
                                {% if  not lesson.dc_price or lesson.dc_price == 0 %}
                                    <h6 class="card-title">{{ lesson.org_price|intcomma }}원</h6>
                                {% else %}
                                    <h6 class="card-title">{{ lesson.dc_price|intcomma }}원 <small>{{ lesson.org_price|intcomma }}원</small></h6>
                                {% endif %}
                                <div class="d-flex justify-content-between">
                                    <p class="badge badge-info">NEW</p>
                                    <p class="badge badge-success">{{ lesson.academy.small_district.big_district }}</p>
                                </div>
                            </div>
                        </a>

                    </div>
                </div>
            {% endfor %}
        </div>

    </section>
    {#    <section id="proceeding_event">#}
    {#        <div style="width: 100%; height: 50px; background-color: #1f7e9a;">#}
    {#            진행중인 이벤트 어쩌구 저쩌구#}
    {#        </div>#}
    {#    </section>#}
{% endblock %}

{% block base_extra_script %}
    <script src="https://unpkg.com/swiper/js/swiper.min.js"></script>
    <script>
        var swiper = new Swiper('.swiper-container', {
            slidesPerView: 1,
            spaceBetween: 30,
            loop: true,
            pagination: {
                el: '.swiper-pagination',
                clickable: true,
            },
            navigation: {
                nextEl: '.swiper-button-next',
                prevEl: '.swiper-button-prev',
            },
        });
        {% if request.user.is_authenticated and not request.user.profile %}
            alert('소셜 계정으로 가입하셔서 미기입된 정보가 있습니다.' +
                '추가 정보를 입력하여 주시기 바랍니다.');location.href="{% url 'profile_create' %}";
        {% endif %}
    </script>
{% endblock %}

core/templates/user/liked_lesson_list.html
{% extends 'user/base.html' %}
{% load staticfiles %}
{% load humanize %}
{% block base_extra_head %}
    <style>
        .wrapper { float: left; clear: left; display: table; table-layout: fixed; }
        img.img-responsive { display: table-cell; max-width: 100%; }
        .card-img-top {
            height: 280px;
        }
        @media screen and (max-width: 600px) {
            .main_menu1_contents{background-color: #F1F3F4; height:180px;}
            .card-img-top {height: 120px;}
        }
        .swiper-slide { text-align: center; font-size: 18px; background: #fff; display: -webkit-box; display: -ms-flexbox; display: -webkit-flex; display: flex; -webkit-box-pack: center; -ms-flex-pack: center; -webkit-justify-content: center; justify-content: center; -webkit-box-align: center; -ms-flex-align: center; -webkit-align-items: center; align-items: center;}
        .card-text {white-space: normal; line-height: 1.2; height: 2.4em; text-align: left; word-wrap: break-word; display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical;
            display: inline-block; width: 100%; overflow: hidden; text-overflow: ellipsis;}
        .elipsis_text {white-space: normal; line-height: 1.2; height: 2.4em; text-align: left; word-wrap: break-word; display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical;
            display: inline-block; width: 100%; overflow: hidden; text-overflow: ellipsis;}
        .elipsis_text2 {white-space: normal; line-height: 1.2; height: 1.2em; text-align: left; word-wrap: break-word; display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical;
            display: inline-block; width: 100%; overflow: hidden; text-overflow: ellipsis;}
        .card-title {font-size: 12px;}
    </style>
{% endblock %}
{% block maincontent %}
    <h5 class="my-3 px-3" style="font-weight: bold; color: #699A3C;">관심 목록</h5>

    <div class="row w-100 mx-0 px-2">
        {% if lessons %}
            {% for lesson in lessons %}
                <div class="col-lg-4 col-md-6 col-sm-6 col-6 p-2">
                    <div class="card" style="background-color: #E7E6E6;">
                        <a href="{% url 'lesson_detail' lesson.id %}" style="text-decoration: none; color: black;">
                            {% if lesson.lessonimage_set.exists %}
                                <img src="{{ lesson.lessonimage_set.first.image.url }}" class="card-img-top" alt="...">
                            {% else %}
                                <img src="{% static 'img/default_lesson_image.png' %}" class="card-img-top" alt="">
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title elipsis_text">{{ lesson.title }}</h5>
                                <p class="elipsis_text2" style="color: #707070; font-size: 12px; font-weight: bold;">{{ lesson.academy.name }}</p>
                                <p class="card-text">{{ lesson.introduction }}</p>
                                {% if  not lesson.dc_price or lesson.dc_price == 0 %}
                                    <h6 class="card-title">{{ lesson.org_price|intcomma }}원</h6>
                                {% else %}
                                    <h6 class="card-title">{{ lesson.dc_price|intcomma }}원 <small>{{ lesson.org_price|intcomma }}원</small></h6>
                                {% endif %}
                                <div class="d-flex justify-content-between">
                                    <p class="badge badge-danger">HOT</p>
                                    <p class="badge badge-success">{{ lesson.academy.small_district.big_district }}</p>
                                </div>
                            </div>
                        </a>

                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h5 class="mx-3">관심 목록이 비었습니다.</h5>
        {% endif %}
    </div>

{% endblock %}
{% block base_extra_script %}
    <script>
        {% if request.user.is_authenticated and not request.user.profile %}
            alert('소셜 계정으로 가입하셔서 미기입된 정보가 있습니다.' +
                '추가 정보를 입력하여 주시기 바랍니다.');location.href="{% url 'profile_create' %}";
        {% endif %}
    </script>
{% endblock %}