board/urls.py
from django.urls import path
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'board'
urlpatterns = [
    path('<str:mid>', views.BoardListView.as_view(), name='board_list'),
    path('board_detail/<int:pk>', views.BoardDetailView.as_view(), name='board_detail'),
    path('document_add/<str:mid>', views.DocumentCreateView.as_view(), name='document_add'),
    path('document_edit/<int:pk>', views.DocumentUpdateView.as_view(), name='document_edit'),
    path('document_delete/<int:pk>', views.DocumentDeleteView.as_view(), name='document_delete'),
    url(r'^file_download/(?P<pk>[0-9]+)/$', views.file_download, name='file_download'),
    url(r'^set_file_delete/$', views.set_file_delete, name='set_file_delete'),
    url(r'^summernote/upload_attachment/$', views.upload_attachment, name='django_summernote-upload_attachment'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include
from django_registration.backends.one_step.views import RegistrationView

from . import views
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/login/', views.redirect_login, name='redirect-login'),
    path('/accounts/password/reset/', views.redirect_password_reset, name='redirect_password_reset'),
    path('login/', views.CustomizedLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    # path('register/', RegistrationView.as_view(success_url='/'), name='django_registration_register'),
    # path('register/', RegistrationView.as_view(form_class=views.MyCustomUserForm, success_url='/'), name='django_registration_register'),

    path('lesson/list/', views.LessonListView.as_view(), name='lesson_list'),

    path('sport/list/', views.SportListView.as_view(), name='sport_list'),
    # path('sport/detail/<int:pk>', views.SportDetailView.as_view(), name='sport_detail'),
    path('lesson/detail/<int:pk>/', views.LessonDetailView.as_view(), name='lesson_detail'),
    path('lesson/list/liked', views.LikedLessonListView.as_view(), name='liked_lesson_list'),

    path('user/create/', views.user_create, name='user_create'),
    path('profile/create/', views.ProfileCreateView.as_view(), name='profile_create'),
    path('profile/update/<int:pk>/', views.ProfileUpdateView.as_view(), name='profile_update'),

    path('like/create_delete/', views.like_create_delete, name='like_create_delete'),

    path('review/delete/', views.review_delete, name='review_delete'),
    path('review/create_update/', views.review_create_update, name='review_create_update'),

    path('wronginfo/create/', views.wronginfo_create, name='wronginfo_create'),

]

dailympic/urls.py
import re

from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url
from board.views import upload_attachment
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

from django.views.static import serve
from django.urls import re_path
import re

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('community/', include('board.urls'), name='community'),
    url(r'^summernote/upload_attachment/$', upload_attachment, name='django_summernote-upload_attachment'),
    path('summernote/', include('django_summernote.urls')),
    # path('',include('social_django.urls', namespace='social'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

board/models.py
from django.db import models
from enum import Enum
from django.contrib.auth.models import User, Group, UserManager
from django_summernote import models as summermodel
from django_summernote.utils import get_attachment_storage, get_attachment_upload_to
from simple_history.models import HistoricalRecords
import os
from functools import partial
import uuid

class ChoiceEnum(Enum):
    @classmethod
    def choices(cls):
        return [(choice.name, choice.value) for choice in cls]

class Board(models.Model):
    class Grant(ChoiceEnum):
        all = '모든 사용자'
        join = '가입한 사용자'
        super = '관리자만'
        group = '선택 그룹 사용자'
    
    board_title = models.CharField(max_length=255, verbose_name='게시판 이름', help_text='게시판 이름을 입력합니다.')
    mid = models.CharField(unique=True, max_length=255, verbose_name='게시판 고유값', help_text='영문+숫자 조합만 가능하며 게시판 주소값입니다. 접근방법예시(127.0.0.1/board/<고유값>)')
    board_description = models.TextField(blank=True, null=True, verbose_name='게시판 설명', help_text='게시판에 대한 간단한 설명을 입력합니다.')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='생성일')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='수정일')
    board_grant = models.CharField(max_length=6, default='all', choices=Grant.choices(), verbose_name='권한 설정', help_text='권한을 설정합니다. 선택그룹사용자 일경우 그룹 권한에 기반합니다.')
    user = models.ManyToManyField(User, through='UserGrant', verbose_name='유저 권한', help_text='유저권한을 부여하면 권한 설정,그룹 권한에 관계없이 최상위 권한으로 동작합니다.')
    denied_word = models.BooleanField(default=True, verbose_name='스팸 키워드', help_text='해당부분을 체크하면 스팸 키워드필터가 적용됩니다.')
    
    def __str__(self):
        return str(self.board_title)
    
    class Meta:
        verbose_name = '게시판'
        verbose_name_plural = '게시판'
    
    
class UserGrant(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='유저 권한')
    board = models.ForeignKey(Board, on_delete=models.CASCADE, verbose_name='게시판')
    grant_list = models.BooleanField(default=False, verbose_name='목록')
    grant_view = models.BooleanField(default=False, verbose_name='글열람')
    grant_write_document = models.BooleanField(default=False, verbose_name='글 작성')
    grant_write_comment = models.BooleanField(default=False, verbose_name='댓글 작성')
    grant_super = models.BooleanField(default=False, verbose_name='관리자', help_text='체크시 모든글에대한 슈퍼유저권한을 가집니다.')
    
    def __str__(self):
        return str(self.user) + '의 유저권한'
    
    class Meta:
        unique_together = ('user', 'board',)
        verbose_name = '유저 권한'
        verbose_name_plural = '유저 권한을 부여하면 권한 설정, 그룹 권한에 관계없이 최상위 권한으로 동작합니다.'
        
        
class Documents(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE, verbose_name='게시판')
    is_notice = models.BooleanField(default=False, verbose_name='공지')
    title = models.CharField(max_length=255, verbose_name='제목')
    content = models.TextField(verbose_name='내용')
    readed_count = models.PositiveIntegerField(default=0, verbose_name='조회수')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='글쓴이')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='생성일')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='수정일')
    ipaddress = models.GenericIPAddressField()
    is_secret = models.BooleanField(default=False, verbose_name='글 비공개')
    comment_is_secret = models.BooleanField(default=False, verbose_name='댓글 비공개')
    history = HistoricalRecords()

    def __str__(self):
        return str(self.board.board_title) + ' - ' + str(self.title)

    class Meta:
        verbose_name = '문서'
        verbose_name_plural = '문서'
    
    
class Comments(models.Model):
    document = models.ForeignKey(Documents, on_delete=models.CASCADE, verbose_name='문서')
    is_secret = models.BooleanField(default=False, verbose_name='댓글 비공개')
    content = models.TextField(verbose_name='내용')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='글쓴이')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='생성일')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='수정일')
    ipaddress = models.GenericIPAddressField()
    
    def __str__(self):
        return str(self.document.board.board_title) + ' - ' + str(self.document.title) + ' 의 댓글'

    class Meta:
        verbose_name = '댓글'
        verbose_name_plural = '댓글'
        
        
def _update_filename(instance, filename, path):

    from datetime import datetime
    today = datetime.now()
    path = path.replace('%Y', today.strftime('%Y'))
    path = path.replace('%m', today.strftime('%m'))
    path = path.replace('%d', today.strftime('%d'))

    file_ext = filename.split('.')
    file_ext = file_ext[len(file_ext) - 1]

    filename = "{}.{}".format(uuid.uuid4(),file_ext)

    return os.path.join(path, filename)

def upload_to(path):
    return partial(_update_filename, path=path)
    
class Files(models.Model):
    document = models.ForeignKey(Documents, on_delete=models.CASCADE, verbose_name='문서')
    file = models.FileField(upload_to=upload_to('file/%Y/%m/%d/'), verbose_name='첨부 자료')
    org_file_name = models.CharField(max_length=255, blank=True, verbose_name='원본파일명')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='생성일')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='수정일')
    
    def __str__(self):
        return str(self.document.title) + ' 의 첨부 파일'

    class Meta:
        verbose_name = '첨부 파일'
        verbose_name_plural = '첨부 파일'
        
        
class Summernote(summermodel.AbstractAttachment):
    document = summermodel.models.ForeignKey(Documents, null=True, blank=True, verbose_name='문서', on_delete=models.CASCADE)
    name = models.CharField(max_length=255, null=True, blank=True, verbose_name='원본파일명', help_text="Defaults to filename, if left blank")
    file = models.FileField(
        upload_to=get_attachment_upload_to(),
        storage=get_attachment_storage(),
        unique=True
    )
    ipaddress = models.GenericIPAddressField(null=True, blank=True)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, verbose_name='글쓴이')

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name = '첨부 이미지'
        verbose_name_plural = '첨부 이미지'


class BoardGroupGrant(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE, verbose_name='그룹')
    board = models.ForeignKey(Board, on_delete=models.CASCADE, verbose_name='게시판')
    grant_list = models.BooleanField(default=False, verbose_name='목록')
    grant_view = models.BooleanField(default=False, verbose_name='글열람')
    grant_write_document = models.BooleanField(default=False, verbose_name='글 작성')
    grant_write_comment = models.BooleanField(default=False, verbose_name='댓글 작성')
    grant_super = models.BooleanField(default=False, verbose_name='관리자', help_text='체크시 해당그룹은 모든글에대한 슈퍼유저권한을 가집니다.')
    
    def __str__(self):
        return str(self.group.name) + '의 그룹권한'
    
    class Meta:
        unique_together = ('board', 'group',)
        verbose_name = '그룹 권한'
        verbose_name_plural = '권한설정에서 선택 그룹 사용자 일때 동작합니다.'
        

class DeniedWord(models.Model):
    word = models.CharField(max_length=255, verbose_name='키워드', help_text='키워드를 입력하세요.')
    hit = models.IntegerField(default=0, verbose_name='스팸횟수')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='생성일')
    
    def __str__(self):
        return '스팸 키워드 - ' + str(self.word)
    
    class Meta:
        verbose_name = '스팸 키워드'
        verbose_name_plural = '스팸 키워드'

board/templates/board/user/alluserboard.html
{% extends 'base.html' %}

{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static "css/board.css" %}">
    {{ form.media }}
    <script>
        var alluser = function () {
            return {
                'setMovePage': function (url) {
                    location.href = url;
                }
            }
        }();
        jQuery(document).ready( function() {
            // error 가 있을시 표시되는 필드 display가 바뀌지않는 버그에 대한 임시처리
            jQuery('.invalid-feedback').show();
        });
    </script>
    {% block alluserboard %}
    {% endblock %}

{% endblock %}

board/templates/board/user/board_detail.html
{% extends 'board/user/alluserboard.html' %}

{% load tz %}

{% block alluserboard %}
    {% timezone "Asia/Seoul" %}
        <div class="col-md-12 mt-5 notice_list">
            <section class="board-view">
                <div class="tit-area">
                    <h3 class="tit">
                        {{ object.title }}
                    </h3>
                </div>

                {% if object.is_secret is False or b_grant.grant_super is True %}
                    {% if object.files_set.all.count > 0 %}
                        <div class="info">
                            <p class="tit">첨부파일</p>
                            <p class="add-file">
                                {% for file in object.files_set.all %}
                                    <a href="{% url 'board:file_download' file.id %}" title="파일 다운로드">
                                        {{ file.org_file_name }}
                                    </a>
                                    <br>
                                {% endfor %}
                            </p>
                        </div>
                    {% endif %}
                {% endif %}

                <div class="cont">
                    {% if object.is_secret and b_grant.grant_super is False and request.user != object.user %}
                        {{ '비공개입니다.'|linebreaks }}
                    {% else %}
                        {{ object.content|safe }}
                    {% endif %}
                </div>
            </section>

        </div>
    {% endtimezone %}


{% endblock %}

board/templates/board/user/board_list.html
{% extends 'board/user/alluserboard.html' %}

{% load widget_tweaks %}
{% load tz %}
{% load staticfiles %}

{% block alluserboard %}
    <div>
        <h4 style="background-color: #699A3C; font-weight: bold; color: white; padding: 5px 10px; margin-top: 20px; display: inline-block;">{{ object_list.first.board.board_title }}</h4>
    </div>

    <div class="mt-4 position-relative">
        {% timezone "Asia/Seoul" %}
            <div>
                <table class="table table-hover">
                    <tbody>
                        {% for document in notice_list %}
                            <tr>
                                <td><a style="font-weight: bold;" href="{% url 'board:board_detail' document.id %}?return_url={{ request.META.PATH_INFO }}?{{ request.META.QUERY_STRING }}">{{ document.title }}</a></td>
                            </tr>
                        {% endfor %}
                        {% for document in object_list %}
                            {% if not document.is_secret or document.user == request.user %}
                                <tr>
                                    <td><a href="{% url 'board:board_detail' document.id %}?return_url={{ request.META.PATH_INFO }}?{{ request.META.QUERY_STRING }}">{{ document.title }}</a></td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        {% endtimezone %}

        {% include 'board/user/paginator.html' %}
    </div>
    <script>
        $(document).ready(function () {
            $('#date_reset').click(function () {
                $('#id_title').val('');
                $('#id_user').val('');
                setTimeout(function() {
                    $('#search_form').submit();
                },10)
            });
        });
    </script>
{% endblock %}

board/templates/board/user/board_widget.html
<div style="width:100%; {{ add_css1 }} overflow: hidden;">
    {% for object in board_obj %}
        <div style="width: 100%; height: 28px; overflow: hidden; cursor: pointer; {{ add_css2 }}" onclick="get_wigdet_link_{{ uuid }}( '{% url 'board:board_detail' object.id %}' );">
            <div style="float: left; width: 65%; overflow:hidden; text-overflow:ellipsis; white-space:nowrap;">
                {% if title_bold == 'Y' %}
                    <strong>- {{ object.title }}</strong>
                {% else %}
                    - {{ object.title }}
                {% endif %}
            </div>
            <div style="float: right; width: 35%; {{ add_css3 }}">
                {% if user_YN == 'Y' %}
                    <div style="float: right; margin-left: 10px; width: 60px; text-align: center; overflow: hidden;">{{ object.user }}</div>
                {% endif %}
                <div style="float: right;">{{ object.created_at|date:format }}</div>
            </div>
        </div>
    {% endfor %}
</div>
<div style="clear: both;"></div>
<script>
    function get_wigdet_link_{{ uuid }}( url ) {
        {% if link_target == '_self' %}
            location.href = url;
        {% else %}
            window.open(url);
        {% endif %}
    }
</script>

board/templates/board/user/document_add.html
{% extends 'board/user/alluserboard.html' %}

{% load widget_tweaks %}
{% load alluser_templatehelpers %}

{% block alluserboard_title %}
    {{ board_obj.board_title }}
{% endblock %}

{% block alluserboard %}
    <div class="col-md-12 mx-auto mt-5">
        <form method='post' action='' enctype="multipart/form-data">
            {% csrf_token %}
            {% for hidden_field in form.hidden_fields %}
                {{ hidden_field }}
            {% endfor %}

            {% if form.non_field_errors %}
                <div class="alert alert-danger" role="alert">
                    <ul>
                        {% for error in form.non_field_errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}

            {% for field in form.visible_fields %}
                <div class="form-group">
                    <div class="col-sm-12 custom-control custom-radio">
                        {% if form.is_bound %}
                            {% if field.errors %}
                                {% if field|get_inputtype:'checkbox' %}
                                    {% render_field field class="custom-control-input" %}
                                    <label class="custom-control-label ml-4" for="{{ field.auto_id }}" style="cursor: pointer">{{ field.label }}</label>
                                {% elif field.auto_id == 'id_content' %}
                                    {{ field }}
                                {% else %}
                                    {% render_field field class="form-control is-invalid" placeholder=field.label %}
                                {% endif %}
                                {% for error in field.errors %}
                                    <div class="invalid-feedback">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            {% else %}
                                {% if field|get_inputtype:'checkbox' %}
                                    {% render_field field class="custom-control-input" %}
                                    <label class="custom-control-label ml-4" for="{{ field.auto_id }}" style="cursor: pointer">{{ field.label }}</label>
                                {% elif field.auto_id == 'id_content' %}
                                    {{ field }}
                                {% else %}
                                    {% render_field field class="form-control is-valid" placeholder=field.label %}
                                {% endif %}
                            {% endif %}
                        {% else %}
                            {% if field|get_inputtype:'checkbox' %}
                                {% render_field field class="custom-control-input" %}
                                <label class="custom-control-label ml-4" for="{{ field.auto_id }}" style="cursor: pointer">{{ field.label }}</label>
                            {% elif field.auto_id == 'id_content' %}
                                {{ field }}
                            {% else %}
                                {% render_field field class="form-control" placeholder=field.label %}
                            {% endif %}
                        {% endif %}
                        {% if field.help_text %}
                            <small class="form-text text-muted">{{ field.help_text }}</small>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}

            {% if files_obj.count > 0 %}
                <div class="form-group mt-4">
                    <label class="col-sm-3 control-label">
                        기존 첨부 파일
                    </label>
                    <div class="col-sm-12">
                        {% for file in files_obj %}
                            <span class="colM mr-3">
                                <a href="{% url 'board:file_download' file.id %}" title="파일 다운로드">
                                    {{ file.org_file_name }}
                                </a>
                                <button type="button" class="close" aria-label="Close" style="float: none;" data-file_id="{{ file.id }}">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </span>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}

            <div class="form-group mt-4">
                <label class="col-sm-3 control-label">
                    첨부 파일 추가
                </label>
                <div class="col-sm-12">
                    <input name="input2" type="file" class="file" multiple data-show-upload="true" data-show-caption="true">
                </div>
            </div>

            <div class="text-center mt-5">
                <button type="button" class="btn btn-warning mr-4" onclick="history.back();">뒤로</button>
                <button type="submit" class="btn btn-primary">저장</button>
            </div>
        </form>

    </div>
    <script>
        $(document).ready(function () {
            $('.kv-upload-progress').hide();
            $('.fileinput-cancel').hide();
            $('.fileinput-upload').hide();

            $('.close').click(function () {
                if( !confirm('파일을 삭제할까요?') ) {
                    return false;
                }

                var $this = $(this);
                var file_id = $this.data('file_id');

                $.ajax({
                    url: '{% url 'board:set_file_delete' %}',
                    type: 'POST',
                    async: true,
                    data: {
                        file_id: file_id,
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                    },
                    cache: false
                }).done(function (data) {
                    alert(data.message);
                    if( data.status === 'true' ) {
                        $this.closest('.colM').remove();
                    }
                }).fail(function (jqXHR, textStatus, errorThrown) {
                    //console.log('fail');
                    alert(jqXHR.status + ' : 시스템에 문제가 있습니다!')
                }).always(function () {
                    //console.log('always');
                });

            });
        });
    </script>
{% endblock %}

board/templates/board/user/error.html
{{ error_message }}

board/templates/board/user/paginator.html
{% load alluser_templatehelpers %}
{% if is_paginated %}
    {% with params=request.GET.urlencode %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">

            <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
                <a class="page-link" href="{% if page_obj.has_previous %}{% relative_url page_obj.previous_page_number 'page' params %}{% endif %}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>

            {% if page_obj.number|add:'-9' > 1 %}
                <li><a class="page-link" href="{% relative_url page_obj.number|add:'-10' 'page' params %}">&hellip;</a></li>
            {% endif %}

            {% for i in page_obj.page_range %}
                {% if page_obj.number == i %}
                    <li class="active page-item"><a class="page-link">{{ i }} <span class="sr-only">(current)</span></a></li>
                {% else %}
                    <li class="'page-item"><a class="page-link" href="{% relative_url i 'page' params %}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}

            {% if page_obj.paginator.num_pages > page_obj.number|add:'9' %}
                <li><a class="page-link" href="{% relative_url page_obj.number|add:'10' 'page' params %}">&hellip;</a></li>
            {% endif %}

            <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
                <a class="page-link" href="{% if page_obj.has_next %}{% relative_url page_obj.next_page_number 'page' params %}{% endif %}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
        </ul>
    </nav>
    {% endwith %}
{% endif %}